name: Docker Image CI

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/dawidwozny/test:latest1

    - name: login to ghcr.io
      run: docker login ghcr.io -u dawidwozny -p ${{ secrets.PAT }}
      
    - name: push
      run: ddocker push ghcr.io/dawidwozny/test:latest1
